pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'javac multi-stage-multi-agent/hello.java'
        sh 'java -cp multi-stage-multi-agent hello'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node multi-stage-multi-agent/app.js'
      }
    }
  }
}
